### ISSUE TITLE
TypeScript version?

### ISSUE THREAD

**Issue by mzhukovs** [chrisvfritz/vue-enterprise-boilerplate#118]
Nice template, really like the aim here. Do you see there being a TS version in the works any time soon? Seems the better way to go for enterprise apps especially. Even Vue itself, with v3, will be moving fully towards TypeScript.

Please let me know, thanks.

**Comment by chrisvfritz** [comment]
I really like TypeScript in libraries, but still prefer JavaScript in most applications [for these reasons](https://github.com/chrisvfritz/vue-enterprise-boilerplate/blob/master/docs/tech.md#javascript-faq). So I'm unlikely to move to TypeScript for the foreseeable future.

However:

- It doesn't take very much work to migrate to TypeScript. You should only need to:

  1. Use `@vue/cli-plugin-typescript` instead of `@vue/cli-plugin-babel` (while deleting `.babelrc.js`).
  1. Update `jsconfig.template.js` and `aliases.config.js` to generate a `tsconfig.json` file instead of `jsconfig.json`.
  1. Configure ESLint to use the [TypeScript parser](https://github.com/eslint/typescript-eslint-parser) instead of Babel.
  1. Similarly, configure Jest to use the [TypeScript parser](https://basarat.gitbooks.io/typescript/docs/testing/jest.html) instead of Babel.
   
- If you mostly just want better type definitions for intellisense, even including type errors, VS Code automatically converts JSDoc to TypeScript definitions to give you just that. See [these two](https://blog.usejournal.com/type-vue-without-typescript-b2b49210f0b) [excellent articles](https://itnext.io/type-vuex-without-typescript-4f183b83a907) by @znck.

- When I eventually upgrade this template to Vue 3, I'll probably migrate components to use the class-based syntax to make migrations to TypeScript much easier.

Does that answer your question? 🙂

**Comment by mzhukovs** [comment]
Certainly does, thanks!
