### ISSUE TITLE
Implement option with GraphQL

### ISSUE THREAD

**Issue by marceloavf** [chrisvfritz/vue-enterprise-boilerplate#119]
Hey @chrisvfritz 

First of all, thank you for this awesome boilerplate.

Have you consider implement GraphQL as an option in this boilerplate? I was wondering to use it and our production server is in Apollo GraphQL and I was trying to use this solution over here: https://github.com/frandiox/vue-graphql-enterprise-boilerplate

But it has a lot of implementation from Auth0, Prisma and complete server solution, but all I need is a mock-api that translate this response to GraphQL and change login communication requests.

Thank you!

**Comment by frandiox** [comment]
@marceloavf Hi! Author of the GraphQL alternative here. I think removing Prisma from that boilerplate is very easy. Auth0 might be a bit more complex just because you need to provide your own auth implementation, but nothing hard either. You can open issues in that repo asking about this and I'll be happy to help 👍

**Comment by chrisvfritz** [comment]
@marceloavf @frandiox For the record, I'm also considering building a vue-enterprise-fullstack-boilerplate, which would similarly include Auth0 and Apollo integration and be structured similarly to [vue-monolith-example](https://github.com/chrisvfritz/vue-monolith-example).

I still need to figure out how exactly I'd want to share work between the two projects though. One worry is that extracting most of the config to a Vue CLI plugin would make the repo less usable as a browsable study guide for best practices. I'm very open to thoughts on this, if anyone has any! 🙂

**Comment by frandiox** [comment]
@chrisvfritz I personally like CLI plugins for installing specific tools like ESLint, Prettier or Jest. However, for things like this, I feel an actual template is better since you can see and understand what's going on instead of relying on a set of black boxes. Perhaps some parts can be extracted as plugins, I guess it's hard to find balance 😅 .

About the new boilerplate, since the stack you mention is quite similar to `vue-graphql-enterprise-boilerplate`, I'd be happy to collaborate on that if you want. It can be moved to an organization or anything if you prefer. I kept the original structure of `vue-enterprise-boilerplate` to make cherry-pick easier from your original repo, but the structure can be changed of course (there's not code sharing between front and back so it's just a matter of moving folders).
