### ISSUE TITLE
Integration with vuex-loading

### ISSUE THREAD

**Issue by jnarowski** [chrisvfritz/vue-enterprise-boilerplate#13]
I haven't used this plugin yet, but certainly have vue state level loading, isLoading etc params riddled across my components. It feels messy but it's quick and dirty. 

Wondering if it would make sense to integrate something like [vue-loading](https://github.com/f/vuex-loading) to handle this in a more clean way?

**Comment by chrisvfritz** [comment]
If the state is really specific to that component, I think keeping it there makes sense. I don't think it really feels dirty to me, but vuex-loading does look like it could be useful for applications that need to keep track of loading states that affect a lot of different components.

I think in all the cases that I've needed something like this, I've been pretty happy creating my own solution though. I do worry that people might use `$isLoading` with an array as an alternative to creating a getter to consolidate that collection of loading states.

Either way, I don't think the problem is complex enough that I would include more complicated loading states in this boilerplate.
