### ISSUE TITLE
Keeping up with dependencies 

### ISSUE THREAD

**Issue by jnarowski** [chrisvfritz/vue-enterprise-boilerplate#49]
Any thoughts as to how one might keep up with dependencies, once the boilerplate is applied to a project? I am using it in a production app, but would love to keep it as close to in-sync with what you have here, especially the fixes and improvements!

**Comment by jnarowski** [comment]
I see you answered this in another thread.

**Comment by chrisvfritz** [comment]
Just dropping [a link to that thread](https://github.com/chrisvfritz/vue-enterprise-boilerplate/issues/46#issuecomment-391164357) here in case anyone else finds this. 🙂

**Comment by stuta** [comment]
yarn upgrade-interactive --latest

* vue-cli 3.0.0-beta.16 seems to break lots of tests

**Comment by chrisvfritz** [comment]
@stuta Yes, that's always to be expected with beta software, which is why the dependency ranges in `package.json` for beta packages are locked. If you decide to manually upgrade beyond what the latest version of this boilerplate supports, you unfortunately have to be prepared to deal with any resulting breakages.
